package com.example.yahoofinancesample.service.responsemodels

data class FinancialData(
    val currentPrice: CurrentPrice,
    val currentRatio: CurrentRatio,
    val debtToEquity: DebtToEquity,
    val earningsGrowth: EarningsGrowth,
    val ebitda: Ebitda,
    val ebitdaMargins: EbitdaMargins,
    val financialCurrency: String,
    val freeCashflow: FreeCashflow,
    val grossMargins: GrossMargins,
    val grossProfits: GrossProfits,
    val maxAge: String,
    val numberOfAnalystOpinions: NumberOfAnalystOpinions,
    val operatingCashflow: OperatingCashflow,
    val operatingMargins: OperatingMargins,
    //val profitMargins: ProfitMarginsX,
    val quickRatio: QuickRatio,
    val recommendationKey: String,
    val recommendationMean: RecommendationMean,
    val returnOnAssets: ReturnOnAssets,
    val returnOnEquity: ReturnOnEquity,
    val revenueGrowth: RevenueGrowth,
    val revenuePerShare: RevenuePerShare,
    val targetHighPrice: TargetHighPrice,
    val targetLowPrice: TargetLowPrice,
    val targetMeanPrice: TargetMeanPrice,
    val targetMedianPrice: TargetMedianPrice,
    val totalCash: TotalCash,
    val totalCashPerShare: TotalCashPerShare,
    val totalDebt: TotalDebt,
    val totalRevenue: TotalRevenue
)