package com.example.yahoofinancesample.service.responsemodels

data class SummaryDetail(
    val algorithm: Any,
    val ask: Ask,
    val askSize: AskSize,
//    val averageDailyVolume10Day: AverageDailyVolume10DayX,
    val averageVolume: AverageVolume,
    val averageVolume10days: AverageVolume10days,
//    val beta: BetaX,
    val bid: Bid,
    val bidSize: BidSize,
//    val circulatingSupply: CirculatingSupplyX,
    val currency: String,
    val dayHigh: DayHigh,
    val dayLow: DayLow,
    val dividendRate: DividendRate,
    val dividendYield: DividendYield,
//    val exDividendDate: ExDividendDateX,
    val expireDate: ExpireDate,
    val fiftyDayAverage: FiftyDayAverage,
    val fiftyTwoWeekHigh: FiftyTwoWeekHigh,
    val fiftyTwoWeekLow: FiftyTwoWeekLow,
    val fiveYearAvgDividendYield: FiveYearAvgDividendYield,
//    val forwardPE: ForwardPEX,
    val fromCurrency: Any,
    val lastMarket: Any,
//    val marketCap: MarketCapX,
    val maxAge: String,
    val maxSupply: MaxSupply,
    val navPrice: NavPrice,
    val `open`: Open,
//    val openInterest: OpenInterestX,
    val payoutRatio: PayoutRatio,
    val previousClose: PreviousClose,
    val priceHint: PriceHint,
    val priceToSalesTrailing12Months: PriceToSalesTrailing12MonthsX,
//    val regularMarketDayHigh: RegularMarketDayHighX,
//    val regularMarketDayLow: RegularMarketDayLowX,
//    val regularMarketOpen: RegularMarketOpenX,
    val regularMarketPreviousClose: RegularMarketPreviousCloseX,
//    val regularMarketVolume: RegularMarketVolumeX,
    val startDate: StartDateX,
//    val strikePrice: StrikePriceX,
    val toCurrency: Any,
//    val totalAssets: TotalAssetsX,
    val tradeable: Boolean,
    val trailingAnnualDividendRate: TrailingAnnualDividendRate,
    val trailingAnnualDividendYield: TrailingAnnualDividendYield,
    val twoHundredDayAverage: TwoHundredDayAverage,
    val volume: Volume,
//    val volume24Hr: Volume24HrX,
//    val volumeAllCurrencies: VolumeAllCurrenciesX,
//    val yield: YieldX,
//    val ytdReturn: YtdReturnX
)